name: Publish to npm

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  publish:
    runs-on: ubuntu-latest
    working-directory: layer/lowcode-lambda-layer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
