name: Node.js Package

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm ci
  #       working-directory: layer/lowcode-lambda-layer
  #     - run: npm test
  #       working-directory: layer/lowcode-lambda-layer

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: layer/lowcode-lambda-layer
      - run: npm publish
        working-directory: layer/lowcode-lambda-layer
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}